### ISSUE TITLE
implement proper login

### ISSUE THREAD

**Issue by JoernT** [eXist-db/usermanager#1]
current version still relies on being logged in already via dashboard. That certainly has to be changed.

Furthermore the user shouldn't see anything when not being an admin.

**Comment by joewiz** [comment]
Until proper login is ready, users should note that login via Dashboard or eXide only works if the "Remember me" checkbox is **un**selected. (See related issue affecting Dashboard https://github.com/eXist-db/dashboard/issues/44.)

**Comment by joewiz** [comment]
When not authenticated, the request to `/user` returns a `403 Forbidden` response - as expected. 

But the request to `/group` returns a `500 Server Error` response. I'm not sure why. It should be a `403` too.

**Comment by JoernT** [comment]
agree - however after rethinking i actually want to refactor that again. Currently the client-side handles the errors and shows a toast. However when not authenticated i want to catch that before the client-side app is even returned. That way less information is exposed in the browser and an attacker cannot inspect the client-side code to find e.g. the endpoints the app is talking to.

**Comment by JoernT** [comment]
login should be functional now.
