### ISSUE TITLE
Login form does not appear

### ISSUE THREAD

**Issue by wolfgangmm** [eXist-db/usermanager#10]
If one is not logged in via the dashboard, a blue login screen shows up, but it has no form to enter credentials.

![image](https://user-images.githubusercontent.com/607433/36076969-2aa7acba-0f64-11e8-8560-b290f0b9690f.png)

This happens on Chrome 63.0.3239.132 and Firefox 57.0 (both Mac)

**Comment by dizzzz** [comment]
and Safari (Latest). I see it a bit different:
- the blue screen appears when the user is logged in on dashboard
- when not logged in, approx the same screen appears in white

**Comment by dizzzz** [comment]
<img width="1006" alt="login" src="https://user-images.githubusercontent.com/1700062/36077021-793a3180-0f65-11e8-9a4e-d1ea5f89b4b3.png">

**Comment by JoernT** [comment]
this should be fixed in 0.15.1
