### ISSUE TITLE
Dependency with FunctX library

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/usermanager#16]
The usermanager is not working for me (as I am behind a firewall) because the FunctX library is missing. Probably we miss a dependency definition here?

- eXist 4.1.0-snaphot (2018-04-06)
- user manager 0.16.4 

see attached trace

[trace.txt](https://github.com/eXist-db/usermanager/files/1883251/trace.txt)

**Comment by JoernT** [comment]
this is fixed in 0.16.4

**Comment by dizzzz** [comment]
@JoernT  I actually reported the issue on v0.16.4! It is clearly in my ticket....

**Comment by JoernT** [comment]
don't know what's wrong - see expath file - the dependency is listed

**Comment by dizzzz** [comment]
maybe... because i do not have any HTTP connection to the outside world, it cannot be resolved? That means that we should provide the XAR file in de 'autodeploy' directory of eXist-db. 

IMO eXist-db should be self containing when it is released.

**Comment by dizzzz** [comment]
@JoernT The new usermanager is not functional in the current develop. Defining a dependancy is OK for installation via the package manager, but this is not sufficient for a 'clean' database (and thus when installed via installer jar)

Action before 4.1 release: fix user manager by installing the missing XAR file in "auto deploy"

<img width="1492" alt="error_500_server_error_and_exist_ _java_ _startup_sh_ _152x24" src="https://user-images.githubusercontent.com/1700062/38695994-2f3d4dd0-3e8e-11e8-8ad3-dcf573d91061.png">

**Comment by JoernT** [comment]
thanks @adamretter for fixing that

**Comment by dizzzz** [comment]
Thanx @me :-)
