### ISSUE TITLE
Cannot delete user

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/usermanager#17]
While trying to reproduce exist-db/exist#101 I found that I cannot delete a user.
There is a popup that the user account has been deleted but it persists even after multiple reboots. 
To reproduce:

- Create a new user "debugger".
- Create a new group "debug".
- Make sure debugger is the only member and manager of debug
- reboot
- log in as admin
(so far so good)

I can now delete the group debug, but not debugger no matter in what sequence, or when I reboot. The group is gone but the user stubbornly refuses to dissappear. 

Usermanager: 0.16.4
exist-db: 4.1.0

**Comment by lguariento** [comment]
I have the same issue; I click on 'delete' user, I get a "Really delete this user?" alert, I click 'OK', and the user is still there. Upon analysing what's happening with the XHR call happening behind the scenes, I see:

```
_handleUserDeleted  myuser index.html:34097:17
XHR GET http://X.X.X.X:8080/apps/usermanager/api/user/
Params: null
Response: { "user" : null }
```
So, it looks like the username is not correctly sent as a parameter during the XHR call. Could this be the cause?

**Comment by ohumbel** [comment]
Still the case here

**Comment by tuurma** [comment]
Hi, sorry @joewiz I only now noticed you have PR for the same thing but meanwhile I've added some replacements for deprecated xmldb calls and noticing problems with deleting (but unaware of this issue) created another PR for this https://github.com/eXist-db/usermanager/pull/23

**Comment by joewiz** [comment]
@tuurma No worries, as long as the fix gets in!
